version: "3"

tasks:
  ping:
    cmds:
      - echo "Pong!"
  test:
    cmds:
      - go test -cover ./...
  lint:
    cmds:
      - golangci-lint run ./...
  run: 
    dotenv: ['.env']
    cmds:
      - go build -o .bin/app cmd/app/main.go 
      - chmod +x .bin/app
      - ./.bin/app 
